version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: '04:00'
    groups:
      dependencies:
        applies-to: version-updates
        exclude-patterns:
          - "mypy"
          - "types-*"
        update-types:
          - "minor"
          - "patch"
      mypy:
        applies-to: version-updates
        patterns:
          - "mypy"
      types:
        applies-to: version-updates
        patterns:
          - "types-*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: '04:00'
